# Generated by Django 5.0.4 on 2024-11-27 05:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceWithCategories',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('space_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_date', models.PositiveIntegerField()),
                ('space_created_at', models.DateTimeField()),
                ('space_updated_at', models.DateTimeField()),
                ('categories', models.TextField()),
            ],
            options={
                'db_table': 'space_with_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'space_category',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('space_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_date', models.PositiveIntegerField()),
                ('space_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('space_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'space',
            },
        ),
        migrations.CreateModel(
            name='SpaceCategoryMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.spacecategory')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.space')),
            ],
            options={
                'db_table': 'space_category_mapping',
            },
        ),
    ]
