# Generated by Django 5.0.4 on 2024-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
