# Generated by Django 5.0.4 on 2024-11-28 02:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0003_booking_booking_check_end_date_gt_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('review_rating__gte', 1), ('review_rating__lte', 5)), name='check_review_rating_range'),
        ),
    ]
