# Generated by Django 5.0.4 on 2024-11-28 04:17

from django.db import migrations

def add_default_categories(apps, schema_editor):
    SpaceCategory = apps.get_model('home', 'SpaceCategory')
    default_categories = [
        {"category_id": 1, "category_name": "회의실"},
        {"category_id": 2, "category_name": "팝업스토어"},
        {"category_id": 3, "category_name": "촬영 장소"},
        {"category_id": 4, "category_name": "파티룸"},
    ]
    for category in default_categories:
        SpaceCategory.objects.update_or_create(
            category_id=category["category_id"],
            defaults={"category_name": category["category_name"]}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_userbookingview'),
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]
    
    