# Generated by Django 5.0.4 on 2024-11-28 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20241128_1317'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE VIEW space_with_category_view AS
                SELECT 
                    s.space_id,
                    s.space_name,
                    s.description,
                    s.address,
                    s.capacity,
                    s.price_per_date,
                    s.user_id,
                    s.space_created_at,
                    s.space_updated_at,
                    GROUP_CONCAT(c.category_name ORDER BY c.category_name SEPARATOR ', ') AS categories
                FROM 
                    space s
                LEFT JOIN 
                    space_category_mapping scm ON s.space_id = scm.space_id
                LEFT JOIN 
                    space_category c ON scm.category_id = c.category_id
                GROUP BY 
                    s.space_id, s.space_name, s.description, s.address, 
                    s.capacity, s.price_per_date, s.user_id, 
                    s.space_created_at, s.space_updated_at;
            """,
            reverse_sql="DROP VIEW IF EXISTS space_with_categories;"
        ),
    ]

