# Generated by Django 5.0.4 on 2024-11-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0007_auto_20241128_1319'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='check_end_date_gt_start_date',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='check_end_date_gte_start_date'),
        ),
        migrations.AlterModelTable(
            name='spacewithcategories',
            table='space_with_category_view',
        ),
    ]
