# Generated by Django 5.0.4 on 2024-11-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_booking_check_end_date_gt_start_date_and_more'),
    ]

    operations = [
        # Trigger 생성 SQL 실행
        migrations.RunSQL(
            """
            CREATE TRIGGER prevent_overlapping_bookings
            BEFORE INSERT ON booking
            FOR EACH ROW
            BEGIN
                DECLARE conflicting_booking_count INT;

                -- 예약 날짜가 겹치는지 확인
                SELECT COUNT(*)
                INTO conflicting_booking_count
                FROM booking
                WHERE NEW.space_id = space_id
                  AND NEW.start_date <= end_date
                  AND NEW.end_date >= start_date;

                -- 예약이 겹칠 경우 에러 발생
                IF conflicting_booking_count > 0 THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = '예약 날짜가 기존 예약과 겹칩니다.';
                END IF;
            END;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS prevent_overlapping_bookings;
            """
        ),
    ]