# Generated by Django 5.0.4 on 2024-11-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20241128_1442'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- 기존 트리거 삭제
            DROP TRIGGER IF EXISTS prevent_overlapping_bookings;

            -- 새로운 트리거 생성
            CREATE TRIGGER prevent_overlapping_bookings
            BEFORE INSERT ON booking
            FOR EACH ROW
            BEGIN
                DECLARE conflicting_booking_count INT;

                -- 예약 날짜가 겹치고 상태가 'Canceled'가 아닌 경우만 확인
                SELECT COUNT(*)
                INTO conflicting_booking_count
                FROM booking
                WHERE NEW.space_id = space_id
                  AND NEW.start_date <= end_date
                  AND NEW.end_date >= start_date
                  AND booking_status NOT IN ('Canceled'); -- 'Canceled' 상태 제외

                -- 예약이 겹칠 경우 에러 발생
                IF conflicting_booking_count > 0 THEN
                    SIGNAL SQLSTATE '45000'
                    SET MESSAGE_TEXT = '예약 날짜가 기존 예약과 겹칩니다.';
                END IF;
            END;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS prevent_overlapping_bookings;
            """
        ),
    ]