# Generated by Django 5.0.4 on 2024-11-28 10:35

from django.db import migrations

def add_default_categories(apps, schema_editor):
    SpaceCategory = apps.get_model('home', 'SpaceCategory')
    default_categories = [
        {"category_id": 5, "category_name": "갤러리"},
        {"category_id": 6, "category_name": "공연장"},
        {"category_id": 7, "category_name": "공유주방"},
        {"category_id": 8, "category_name": "스튜디오"},
    ]
    for category in default_categories:
        SpaceCategory.objects.update_or_create(
            category_id=category["category_id"],
            defaults={"category_name": category["category_name"]}
        )
    
class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20241128_1538'),
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]



