# Generated by Django 5.0.4 on 2024-11-28 12:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20241128_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('payment_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.booking')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
