# Generated by Django 5.1.3 on 2024-11-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_payment'),
    ]

    operations = [
        migrations.RunSQL(
           sql = """
            CREATE INDEX idx_space_name ON space(space_name);
            CREATE INDEX idx_category_space ON space_category_mapping(category_id, space_id)
            """,
        ),

    ]
