# Generated by Django 5.1.3 on 2024-11-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20241130_0049'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER udate_payment_status
            AFTER UPDATE ON Booking
            FOR EACH ROW
            BEGIN
                IF NEW.booking_status = 'Canceled' THEN
                    UPDATE Payment SET payment_status = 'Failed' WHERE booking_id = NEW.booking_id;
                END IF;
            END;
            """
        ),
    ]
