# Generated by Django 5.1.3 on 2024-11-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20241130_0141'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW space_review_avg_view AS
            SELECT
                space_id,
                AVG(review_rating) AS average_rating
            FROM Review
            GROUP BY space_id;
            """
        ),

        migrations.RunSQL(
            sql = """
            ALTER TABLE Space
            MODIFY COLUMN image TEXT;
            """,
        ),
    ]
