# Generated by Django 5.0.4 on 2024-11-29 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241130_0000'),
        ('home', '0015_auto_20241130_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceReviewAvg',
            fields=[
                ('space', models.OneToOneField(db_column='space_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.space')),
                ('average_rating', models.FloatField()),
            ],
            options={
                'db_table': 'space_review_avg_view',
                'managed': False,
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'space'), name='unique_user_space_review'),
        ),
    ]
