# Generated by Django 5.1.3 on 2024-11-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_spacereviewavg_review_unique_user_space_review'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE space_category_mapping
            ADD CONSTRAINT unique_space_category UNIQUE (space_id, category_id);
            """
        ),
    ]
