# Generated by Django 5.1.3 on 2024-11-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20241130_0309'),
    ]

    operations = [
    ]
