# Generated by Django 5.1.3 on 2024-11-29 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20241130_0532'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_user_space_review',
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.booking'),
        ),
    ]
