# Generated by Django 5.1.3 on 2024-11-30 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_review_unique_user_space_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='space',
        ),
    ]
