# Generated by Django 5.1.3 on 2024-11-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_review_space'),
    ]

    operations = [
        # 기존 뷰 삭제
        migrations.RunSQL(
            sql="DROP VIEW IF EXISTS space_review_avg_view;",
            reverse_sql="CREATE VIEW space_review_avg_view AS SELECT space_id, AVG(review_rating) AS average_rating FROM Review GROUP BY space_id;"
        ),
        # 새 뷰 생성
        migrations.RunSQL(
            sql="""
            CREATE VIEW space_review_avg_view AS
            SELECT
                b.space_id,
                AVG(r.review_rating) AS average_rating
            FROM Review r
            JOIN Booking b ON r.booking_id = b.booking_id
            GROUP BY b.space_id;
            """,
            reverse_sql="DROP VIEW IF EXISTS space_review_avg_view;"
        ),
    ]
