# Generated by Django 5.1.3 on 2024-11-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20241130_2144'),
    ]

    operations = [
        migrations.RunSQL(
            sql = """
            ALTER TABLE Booking
            MODIFY COLUMN booking_status ENUM('Pending', 'Confirmed', 'Canceled') NOT NULL;
            """,
        ),

        migrations.RunSQL(
            sql = """
            ALTER TABLE Payment
            MODIFY COLUMN payment_method ENUM('Credit Card', 'Debit Card', 'Bank Transfer', 'Mobile Payment') NOT NULL;
            """,
        ),

        migrations.RunSQL(
            sql = """
            ALTER TABLE Payment
            MODIFY COLUMN payment_status ENUM('Success', 'Failed') NOT NULL;
            """,
        ),
    ]
