# Generated by Django 5.0.4 on 2024-11-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(max_length=10)),
                ('user_created_at', models.DateTimeField()),
                ('user_updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
