# Generated by Django 5.0.4 on 2024-11-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='company_name',
            field=models.CharField(blank=True, default='개인', max_length=100, null=True),
        ),
    ]
