# Generated by Django 5.1.3 on 2024-11-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql = """
            ALTER TABLE User
            MODIFY COLUMN role ENUM('host', 'guest') NOT NULL;
            """,
        ),

        migrations.RunSQL(
            sql = """
            CREATE INDEX idx_email_role ON User(email, role);
            CREATE INDEX idx_email ON User(email);
            """
        ),
    ]
