# Generated by Django 5.1.3 on 2024-11-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20241130_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='host_rating',
        ),
    ]
