# Generated by Django 5.0.4 on 2024-11-27 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_host_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='company_name',
            field=models.CharField(default='개인', max_length=100, null=True),
        ),
    ]
